config/routes.rb
Rails.application.routes.draw do
  get '/catalog' => 'catalog#index', as: 'catalog'
  get '/catalog/book/:id', to: 'catalog#show', as: 'catalog_show'
  get '/' => 'home#index', as: 'home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :author_book
  has_many :books, :through => :author_book
end

app/models/author_book.rb
# frozen_string_literal: true

class AuthorBook < ApplicationRecord
  belongs_to :author
  belongs_to :book
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :author_book
  has_many :author, :through => :author_book
  belongs_to :category
  has_many :book_review
  has_many :review, :through => :book_review
  has_many :book_photos
  accepts_nested_attributes_for :book_photos
end

app/models/book_photo.rb
class BookPhoto < ApplicationRecord
  belongs_to :book
end

app/models/book_review.rb
# frozen_string_literal: true

class BookReview < ApplicationRecord
  belongs_to :review
  belongs_to :book
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :books
end

app/models/review.rb
# frozen_string_literal: true

class Review < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :review
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/catalog_controller.rb
class CatalogController < ApplicationController
  # helper_method :sort_column, :sort_direction

  def index
    @categorys = Category.all
    @books = if params[:id]
               @selected_category_id = params[:id]
               Category.find_by(id: params[:id]).books.order("#{sort_column} #{sort_direction}")
             else
               Book.all.limit(12).order("#{sort_column} #{sort_direction}")
             end
  end

  def show
    @current_user
    @path_to_back = request.referer
    @categorys = Category.all
    @book = Book.find_by(id: params[:id])
  end

  private

  def sortable_columns
    %w[title price sales_count created_at]
  end

  def sort_column
    sortable_columns.include?(params[:column]) ? params[:column] : 'title'
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : 'asc'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @categorys = Category.all
    @latest_books = Book.order('created_at DESC').first(3)
    @best_sellers = Book.order('sales_count DESC').first(4)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/catalog/index.html.erb
<!DOCTYPE html>
<html>
  <%= render 'parts/head' %>
  <body>
    <%= render 'parts/header' %>
    <main class="container">
      <h1 class="general-title-margin">Сatalog</h1>
      <div class="hidden-xs clearfix">
        <div class="dropdowns pull-right">
          <div class="dropdown width-240">
            <a href="#" data-toggle="dropdown" role="button" aria-haspopup="true" id="dropdownMenuLink" aria-expanded="false" class="dropdown-toggle lead small">
              Newest first
              <i class="fa fa-angle-down dropdown-icon pull-right"></i>
            </a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to 'Newest first', catalog_path(id: @selected_category_id, column: "created_at") %>
              <li>
                <%= link_to 'Popular first', catalog_path(id: @selected_category_id, column: "sales_count") %>
              </li>
              <li>
                <%= link_to 'Price: Hight to low', catalog_path(id: @selected_category_id, column: "price", direction: "desc") %>
              </li>
              <li>
                <%= link_to 'Price: Low to hight', catalog_path(id: @selected_category_id, column: "price") %>
              </li>
              <li>
                <%= link_to 'Title: A - Z', catalog_path(id: @selected_category_id, column: "title") %>
              </li>
              <li>
                <%= link_to 'Title: Z - A', catalog_path(id: @selected_category_id, column: "title", direction: "desc") %>
              </li>
            </ul>
          </div>
        </div>
        <ul class="list-inline pt-10 mb-25 mr-240">
          <li class="mr-35">
            <%= link_to catalog_path, class: "filter-link" do %>
              All
              <span class="badge general-badge">
                <%= Category.all.map(&:books).flatten.size %>
              </span>
            <% end %>
          </li>
          <% @categorys.each do |category| %>
          <li class="mr-35">
            <%= link_to catalog_path(id: category.id), class: "filter-link" do %>
                <%= category.title %>
                <span class="badge general-badge"><%= category.books.count %></span>
            <% end %>
          </li>
          <% end %>
        </ul>
      </div>


      <div class="mb-120">
        <div class="row">
          <% @books.first(4).each do |book| %>
              <div class="col-xs-6 col-sm-3">
                <div class="general-thumb-wrap">
                  <div class="thumbnail general-thumbnail">
                    <%= image_tag book.book_photos.first.imagen %>
                    <div class="thumb-hover">
                      <div class="general-thumb-link-wrap">
                      	 <%= link_to catalog_show_path(id: book.id), class: "thumb-hover-link" do %>
	                         <i aria-hidden="true" class="fa fa-eye thumb-icon"></i>
	                       <% end %>
                        <a href="#" class="thumb-hover-link">
        <i class="fa fa-shopping-cart thumb-icon"></i></a></div>
                    </div>
                  </div>
                </div>
                <div class="general-thumb-info">
                  <p class="title"><%= book.title %></p>
                  <p class="font-16 in-gold-500">€<%= book.price %></p>
                  <span class="divider-sm"></span>
                  <p class="lead small"><%= book.author.map { |author| author.first_name + ' ' + author.last_name }.join(", ") %></p>
                </div>
              </div>
              <% end %>
        </div>
        <div class="row mb-25">
          <% @books.offset(4).first(4).each do |book| %>
              <div class="col-xs-6 col-sm-3">
                <div class="general-thumb-wrap">
                  <div class="thumbnail general-thumbnail">
                    <%= image_tag book.book_photos.first.imagen %>
                    <div class="thumb-hover">
                      <div class="general-thumb-link-wrap">
                        <%= link_to catalog_show_path(id: book.id), class: "thumb-hover-link" do %>
	                         <i aria-hidden="true" class="fa fa-eye thumb-icon"></i>
	                       <% end %>
                        <a href="#" class="thumb-hover-link">
                          <i class="fa fa-shopping-cart thumb-icon"></i>
                        </a>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="general-thumb-info">
                  <p class="title"><%= book.title %></p>
                  <p class="font-16 in-gold-500">€<%= book.price %></p>
                  <span class="divider-sm"></span>
                  <p class="lead small"><%= book.author.map { |author| author.first_name + ' ' + author.last_name }.join(", ") %></p>
                </div>
              </div>
              <% end %>
        </div>

        <div class="text-center">
          <button class="btn btn-primary">View More</button>
        </div>
      </div>
    </main>
    <%= render 'parts/footer' %>
  </body>

</html>

app/views/catalog/show.html.erb
<!DOCTYPE html>
<html>
  <%= render 'parts/head' %>
  <body>
    <%= render 'parts/header' %>
    <main class="container">
      <%= link_to @path_to_back, class: "general-back-link" do %>
          <i class="fa fa-long-arrow-left mr-15"></i>
        Back to results
      <% end %>
      <div class="row">
        <div class="col-sm-6">
          <div class="product-gallery">
            <div class="mb-20">
              <%= image_tag @book.book_photos.first.imagen, class: "img-responsive"  %>
            </div>
            <div class="images clearfix">
             <% @book.book_photos.offset(1).each do |book| %>    
              <a href="#" class="img-link">
                <%= image_tag book.imagen %>
              </a>
              <% end %>
            </div>
          </div>
        </div>
        <div class="col-sm-6">
          <h1 class="mt-res-0"><%= @book.title %></h1>
          <p class="lead small"><%= @book.author.map { |author| author.first_name + ' ' + author.last_name }.join(", ") %></p>
          <div class="row">
            <div class="col-xs-12 col-md-4">
              <p class="h1 in-gold-500 mt-10">€<%= @book.price %></p>
            </div>
            <div class="col-xs-5 col-md-3">
              <div class="input-group general-position">
                <a href="#" class="input-link">
                    <i class="fa fa-minus line-height-40"></i>
                </a>
                <input type="text" class="form-control quantity-input" />
                <a href="#" class="input-link">
                  <i class="fa fa-plus line-height-40"></i>
                </a>
              </div>
            </div>
            <div class="col-xs-7 col-md-5">
              <button class="btn btn-default pull-right general-position">Add to Cart</button></div>
          </div>
          <div class="general-info-wrap divider-lg">
            <p>Description</p>
            <p class="lead small line-height-2"><%= @book.description  %></p>
          </div>
          <div class="general-info-wrap divider-lg">
            <div class="clearfix">
              <p class="pull-left">Year of publication</p>
              <p class="lead small pull-right"><%= @book.publication_year %></p>
            </div>
          </div>
          <div class="general-info-wrap divider-lg">
            <div class="clearfix">
              <p class="pull-left">Dimensions</p>
              <p class="lead small pull-right">H:<%= @book.dimentions %>" x W: <%= @book.dimentions %>" x D: <%= @book.dimentions %></p>
            </div>
          </div>
          <div class="general-info-wrap divider-lg">
            <div class="clearfix">
              <p class="pull-left">Materials</p>
              <p class="lead small pull-right"><%= @book.material %></p>
            </div>
          </div>
        </div>
      </div>

      <% if @current_user %>
      <div class="mb-80">
        <h3>Write a Review</h3>
        <p class="general-info-text">Score</p>
        <div class="mb-15">
          <i class="fa fa-star rate-empty"></i>
          <i class="fa fa-star rate-empty"></i>
          <i class="fa fa-star rate-empty"></i>
          <i class="fa fa-star rate-empty"></i>
          <i class="fa fa-star rate-empty"></i>
        </div>
        <form class="row">
          <div class="col-md-8">
            <div class="mb-40">
              <div class="form-group">
                <label for="title" class="control-label input-label in-grey-600">Title</label>
                <input id="title" name="title" type="text" class="form-control" /></div>
              <div class="form-group">
                <label for="review" class="control-label input-label in-grey-600">Review</label>
                <textarea id="review" name="review" type="text" class="form-control"></textarea></div>
            </div>
            <div class="text-right">
              <button class="btn disabled mb-20">Post</button></div>
          </div>
        </form>
      </div>
      <% end %>
      
      
      <% if @book.book_review.size > 0 %>
      <div class="mb-80">
        <h3 class="in-gold-500 mb-25">Reviews (3)</h3>
        <div class="general-message-wrap divider-lg">
          <div class="clearfix">
            <img src="https://www.smashingmagazine.com/wp-content/uploads/2015/09/smashing-book-5-2-large.jpg" class="img-circle logo-size inlide-block pull-left" />
            <div class="ml-70">
              <div>
                <div class="general-message-date hidden-xs">11/11/16</div>
                <div class="max-240">
                  <div class="general-message-verified">Verified Reviewer</div>
                  <div class="general-message-name">Rita J. Lewis</div>
                </div>
              </div>
              <div class="mb-15">
                <i class="fa fa-star rate-star"></i>
                <i class="fa fa-star rate-star"></i>
                <i class="fa fa-star rate-star"></i>
                <i class="fa fa-star rate-star"></i>
                <i class="fa fa-star rate-star"></i></div>
              <p>Thank you BookStore, I was very pleased to receive my order for the Moleskine diary so soon after placing the order.</p>
            </div>
          </div>
        </div>
        <div class="general-message-wrap divider-lg">
          <div class="clearfix">
            <span class="img-circle logo-size inlide-block pull-left logo-empty">M</span>
            <div class="ml-70">
              <div>
                <div class="general-message-date hidden-xs">11/11/16</div>
                <div class="max-240">
                  <div class="general-message-verified pull-right">Verified Reviewer</div>
                  <div class="general-message-name">May J. Novoa</div>
                </div>
              </div>
              <div class="mb-15">
                <i class="fa fa-star rate-star"></i>
                <i class="fa fa-star rate-star"></i>
                <i class="fa fa-star rate-star"></i>
                <i class="fa fa-star rate-star"></i>
                <i class="fa fa-star rate-star rate-empty"></i></div>
              <p>If ‘Get a better job’ had landed on my desk a year ago, I might have been dismissive of it. Instead I was prepared to be open-minded. There have been many occasions where I turned to career books with practical activities to look for some
                inspiration when developing education activities for learners or assessment.</p>
            </div>
          </div>
        </div>
      </div>
      <% end %>
    </main>
    <%= render 'parts/footer' %>
  </body>
</html>

app/views/home/index.html.erb
<!DOCTYPE html>
<html>

<%= render 'parts/head' %>

  <body>
    <%= render 'parts/header' %>
    <main class="container">
      <div id="slider" data-ride="carousel" class="carousel slide">
        <ol class="carousel-indicators">
          <li data-target="#slider" data-slide-to="0" class="active"></li>
          <li data-target="#slider" data-slide-to="1"></li>
        </ol>


        <div role="listbox" class="carousel-inner">

          <% @latest_books.each_with_index do |book, index| %>
          <% if index == 0 %>
          <div class="item active">
          <% else %>
            <div class="item">
          <% end %>
            <div class="row">
              <div class="col-sm-5">
                <div class="general-img-wrap">
                  <%= image_tag book.book_photos.first.imagen, alt: "design-book", class: "img-shadow general-thumbnail-img" %>
                </div>
              </div>
              <div class="col-sm-7">
                <div class="mb-60">
                  <h1><%= book.title %></h1>
                  <p class="lead"><%= book.description%></p>
                  <p class="lead small"><%= book.author.map { |author| author.first_name + ' ' + author.last_name }.join(", ") %></p>
                  <div class="general-align">
                    <button class="disabled btn">Buy Now</button></div>
                </div>
              </div>
            </div>
          </div>
          <% end %>

        </div>


        <a href="#slider" role="button" data-slide="prev" class="left carousel-control">
          <span aria-hidden="true" class="icon-prev"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a href="#slider" role="button" data-slide="next" class="right carousel-control">
          <span aria-hidden="true" class="icon-next"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </main>
    <div class="container">
      <div class="jumbotron text-center mb-0">
        <h2 class="h1">Welcome to our amazing Bookstore!</h2>
        <div class="mb-res-50">
          <p>We pore through hundreds of new books each month and select the five best we can find to share with our members.</p>
        </div>
        <%= button_to 'Get Started', catalog_path, method: :get, class: "btn btn-default" %>
      </div>
      <div class="mb-35">
        <h3>Best Sellers</h3>
        <div class="row">

          <% @best_sellers.first(4).each do |book| %>
          <div class="col-sm-6 col-md-3">
            <div class="general-thumb-wrap">
              <div class="thumbnail general-thumbnail">
                <%= image_tag book.book_photos.first.imagen %>
                <div class="thumb-hover">
                  <div class="general-thumb-link-wrap">
                    <%= link_to catalog_show_path(id: book.id), class: "thumb-hover-link" do %>
	                    <i aria-hidden="true" class="fa fa-eye thumb-icon"></i>
	                  <% end %>
                    <a href="#" class="thumb-hover-link">
                      <i class="fa fa-shopping-cart thumb-icon"></i>
                    </a>
                  </div>
                </div>
              </div>
            </div>
            <div class="mb-35">
              <div class="clearfix">
                <p class="pull-right font-16 in-gold-500">€<%= book.price %></p>
                <p class="title mr-55"><%= book.title %></p>
              </div>
              <span class="divider-sm"></span>
              <p class="lead small"><%= book.author.map { |author| author.first_name + ' ' + author.last_name }.join(", ") %></p>
            </div>
          </div>
          <% end %>


        </div>
      </div>
    </div>
        <%= render 'parts/footer' %>
  </body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookstore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/parts/_footer.html.erb
<footer class="navbar-inverse">
  <div class="container">
    <div class="row">
      <div class="col-sm-9">
        <ul class="list-inline general-align mb-25">
          <li>
            <%= link_to "Home", home_path, class: "nav-link" %>
          </li>
          <li>
            <a href="#" class="nav-link">Shop</a></li>
          <li>
            <a href="#" class="nav-link">Orders</a></li>
          <li>
            <a href="#" class="nav-link">Settings</a></li>
        </ul>
      </div>
      <div class="col-sm-3">
        <p class="general-nav-mail">support@bookstore.com</p>
        <p class="general-nav-number">(555)-555-5555</p>
        <ul class="list-inline general-align">
          <li>
            <a href="#" class="nav-link">
<i aria-hidden="true" class="fa fa-facebook"></i></a></li>
          <li>
            <a href="#" class="nav-link">
<i aria-hidden="true" class="fa fa-twitter"></i></a></li>
          <li>
            <a href="#" class="nav-link">
<i aria-hidden="true" class="fa fa-google-plus"></i></a></li>
          <li>
            <a href="#" class="nav-link">
<i aria-hidden="true" class="fa fa-instagram"></i></a></li>
        </ul>
      </div>
    </div>
  </div>
</footer>
<%= javascript_include_tag 'jquery.js' %>
<%= javascript_include_tag 'bootstrap.js' %>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Readmore.js/2.2.0/readmore.js"></script>
<%= javascript_include_tag 'custom.js' %>
<%= javascript_include_tag 'https://use.fontawesome.com/67602d7308.js' %>

app/views/parts/_head.html.erb
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width" />
  <title>Bookstore</title>
  <%= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Open+Sans' %>
  <%= stylesheet_link_tag 'style.css' %>
</head>

app/views/parts/_header.html.erb
<header class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" data-toggle="collapse" data-target="#navbar" class="navbar-toggle pull-left">
<span class="sr-only"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span></button>
      <a class="navbar-brand">Bookstore</a>
      <a href="#" class="shop-link pull-right visible-xs">
<span class="shop-icon">
<span class="shop-quantity">3</span></span></a></div>
    <a href="#" class="shop-link pull-right hidden-xs">
<span class="shop-icon">
<span class="shop-quantity">3</span></span></a>
    <div id="navbar" aria-expanded="false" class="navbar-collapse collapse pl-30">
      <div class="visible-xs">
        <button type="button" aria-label="Close" class="close">
<span aria-hidden="true">&times;</span></button>
        <ul class="nav navbar-nav">
          <li>
            <%= link_to "Home", home_path %>
          </li>
          <li>
            <a type="button" data-toggle="collapse" href="#menu" aria-expanded="false" aria-controls="menu">Shop</a>
            <ul id="menu" aria-expanded="false" class="collapse list-unstyled pl-30 mb-10">
              <% @categorys.each do |category| %>
                <li>
                  <%= link_to catalog_path(id: category.id), class: "collapse-link" do %>
                    <%= category.title %>
                  <% end %>
                </li>
                <li>
                  <% end %>
            </ul>
            </li>
            <li>
              <a href="#">My account</a></li>
        </ul>
      </div>
      <div class="hidden-xs">
        <ul class="nav navbar-nav">
          <li>
            <%= link_to "Home", home_path %>
          </li>
          <li class="dropdown">
            <a href="#" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" class="dropdown-toggle">Shop</a>
            <ul class="dropdown-menu">
              <% @categorys.each do |category| %>
              <li>
                <%= link_to catalog_path(id: category.id), class: "collapse-link" do %>
                  <%= category.title %>
                <% end %>
              </li>
              <% end %>
              <li role="separator" class="divider"></li>

              <li>
                <a href="#">Log out</a></li>
            </ul>
          </li>
          <li>
            <a href="#">My account</a></li>
        </ul>
      </div>
    </div>
  </div>
</header>